# fly.toml app configuration file generated for epic-esports on 2023-12-17T17:33:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "epic-esports"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/data"