// This file is generated by npm run build:icons

export type IconName =
	| "youtube-logo"
	| "twitter-logo"
	| "twitch-logo"
	| "reddit"
	| "magnifying-glass"
	| "link-2"
	| "instagram-logo"
	| "hourglass"
	| "hamburger-menu"
	| "frame"
	| "facebook-logo"
	| "epic-esports"
	| "chevron-left"
	| "chevron-down"
